#!/bin/bash

# trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

trap "echo \"killed\" && kill 0" EXIT

# run Server
echo "Starting the server"
cabal new-run exes -- --host --ip 127.0.0.1 --p 3000 --name name | sed "s/^/[Server] /" &
# cabal new-run exes -- --host --ip 127.0.0.1 --p 3000 --name name &

# run Clients

read -n 1 -s -r -p $'Press any key to start clients\n'

if [ -n "$1" ]; then
    echo "Running $1 clients"
    N=$1
else
    echo "Running 2 clients (default). Run with any number as argument to set the number of clients to start"
    N=2
fi

for i in $(seq 1 $N)
do
    PORT=$((3000+$i))
    echo "Starting client $i on port $PORT"

    cabal new-run exes -- --ip 127.0.0.1 --p $PORT --name name --s 127.0.0.1:3000:0 --nick $i | sed "s/^/[Client$i] /" &
    # cabal new-run exes -- --ip 127.0.0.1 --p $PORT --name name --s 127.0.0.1:3000:0 --nick $i &
done

read -n 1 -s -r -p $'Press any key to exit\n'

